language: python
python:
  - '3.6'
services:
  - docker
env:
  - TORTUGA_BUILD_DOCKER="true"
before_install:
  - docker pull puppet/puppet-agent
install:
  - pip install tox
  - pip install -r requirements.txt
  - paver build
script:
  - tox -c src/core/tox.ini
  - tox -c src/installer/tox.ini
deploy:
  provider: releases
  api_key:
    secure: u4TkkTEDmeALWodwzNyjQDX5R2N49/NSHGu8vmqIV5ewosnyz/dyQFZPbAIlMSa2+hescRGG3LidUxqrLr8KMNehrE1rVlWfR2DqiNlFL8JT8plH92G66JWPgXgFfLMlXnI0o7vbSfSphBx6gC4udVKl/9/2BWhK6lNFHcXIy0iiv2UCTdlfmrzHERS//zNA7EsEDZ2518JniVcL0vVZ7aQlhpqBnbHBJzrIbIlVhM7UobMOtpkqZ5XttaXlHi/pDdK3YW5lJtfZI73CfekDXogT+0xxCuHS6CrWWAvtaYciuVWFL9hDKuECdu2UN/BgdpsmQba/gJ18WqFVYklyboyCLqpUnhHNcCJARD+y2OX0SavnlObMMzY+4tGm3FFDi7sklY14phyiechjetLZ13WgSxu7T7J9HDlOMt7kjw3LCfnAnJ0lhmsv3ZDZJe2myhibbl1RNzi+cAFADebwK+5ZoE6R2TDfTM7LIi2WgNEk4jFZwdboqVNhlx/wSot6vc6/Biy2DMXLFj7vSt9rEEZReiFSrsVbY4z4KIqVUznQa4xA3RuLI+DVWg3Bb8JgOpyDl4iml72+orzM8lpZb/6UTyWd7ojY6gvlzL2Ja40w/zLaJFLJPEd2qchi54HTdqeasdfLGzqz9dW3pKspzuvOpcVKkesNpbnQS6cTJaU=
  file_glob: true
  file: "dist/tortuga*.tar.bz2"
  skip_cleanup: true
  on:
    all_branches: true
